Repository Arquisoft/wiq_es3b, pull requests merged in 2024-03, with the labels that each got.

#69 Actualización interfaz y preguntas
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Game.jsx
  webapp/src/components/Nav.jsx
  webapp/src/components/Participation.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Start.jsx
  webapp/src/css/Start.css
  webapp/src/css/index.css
  webapp/src/index.js
  webapp/src/test/Game.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/Participation.test.js
  webapp/src/test/PostGame.test.js
  webapp/src/test/Start.test.js
  webapp/src/test/User.test.js
Labels: front-end

#75 Error fixed in deployment
  .github/workflows/release.yml
Labels: bug

#76 Another error solved in deployment
  .github/workflows/build.yml
  .github/workflows/release.yml
  gameservice/game-model.js
  gameservice/game-service.js
  gameservice/game-service.test.js
  gameservice/package-lock.json
  gameservice/package.json
  gatewayservice/gateway-service.test.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question-model.js
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: bug

#87 Uo287747 develop
  webapp/src/App.js
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/index.css
  webapp/src/test/Game.test.js
  webapp/src/test/PostGame.test.js
  webapp/src/test/Start.test.js
Labels: front-end

#114 Question automator created, more templates added to the "geography" category and storage of the generated questions.
  docker-compose.yml
  question_generator/geography/cities/citiesQuestions.js
  question_generator/geography/cities/citiesTemplates.js
  question_generator/locales/en.json
  question_generator/locales/es.json
  question_generator/queryExecutor.js
  question_generator/questionGenerationService.js
  question_generator/questionGenerationService.test.js
  question_generator/questions-utils.js
  question_generator/sports/tennis/tennisTemplates.js
  questionservice/question-model.js
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: back-end

#117 Question information API working
  gatewayservice/gateway-service.js
  questionservice/question-service.js
Labels: back-end

#122 Documentación a develop
  docs/images/GameView.png
  docs/images/HomeView.png
  docs/images/deploymentDiagramWIQ.svg
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
Labels: documentation

#126 Templates added for planets and geography categories
  docs/images/deploymentDiagramWIQ.svg
  question_generator/geography/autonomous_communities_spain/autonomousCommunitiesSpainQuestions.js
  question_generator/geography/autonomous_communities_spain/autonomousCommunitiesSpainTemplates.js
  question_generator/geography/geographyTemplate.js
  question_generator/locales/en.json
  question_generator/locales/es.json
  question_generator/planets/planetsQuestions.js
  question_generator/planets/planetsTemplates.js
Labels: back-end

#123 Uo287747 develop to develop
  webapp/src/App.jsx
  webapp/src/SessionContext.js
  webapp/src/assets/defaultImgProfile.jpg
  webapp/src/assets/sonidoOFF.png
  webapp/src/assets/sonidoON.png
  webapp/src/audio/correct.mp3
  webapp/src/audio/incorrect.mp3
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/Participation.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Start.jsx
  webapp/src/css/index.css
  webapp/src/index.js
  webapp/src/test/App.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/Question.test.js
  webapp/src/test/SessionContext.test.js
  webapp/src/test/Start.test.js
  webapp/src/test/User.test.js
Labels: front-end
