Repository Arquisoft/wiq_es3b, pull requests merged in 2024-02, with the labels that each got.

#31 Update 02_architecture_constraints.adoc
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#32 Update 01_introduction_and_goals.adoc
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#33 Question generator
  package-lock.json
  package.json
  question_generator/cities/citiesQuestions.js
  question_generator/cities/citiesTemplates.js
  question_generator/package-lock.json
  question_generator/package.json
  question_generator/planets/planetsQuestions.js
  question_generator/planets/planetsTemplates.js
  question_generator/queryExecutor.js
  question_generator/questionService.js
  question_generator/questionTemplate.js
Labels: back-end

#45 Documentation
  docs/images/10-Quality_Tree.png
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_system_scope_and_context.adoc
  docs/src/04_solution_strategy.adoc
  docs/src/05_building_block_view.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/08_concepts.adoc
  docs/src/09_architecture_decisions.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/11_technical_risks.adoc
  docs/src/12_glossary.adoc
Labels: documentation

#47 Update 04_solution_strategy.adoc
  docs/src/04_solution_strategy.adoc
Labels: documentation

#53 Primera versión funcional de la interfaz del menú
  docker-compose.yml
  docs/images/GameView.png
  docs/images/StartView.png
  docs/images/UserView.png
  docs/src/03_system_scope_and_context.adoc
  docs/src/04_solution_strategy.adoc
  package-lock.json
  package.json
  webapp/Dockerfile
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/assets/react.svg
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/Start.css
  webapp/src/css/User.css
  webapp/src/css/index.css
  webapp/src/index.css
  webapp/src/index.js
  webapp/src/logo.svg
  webapp/src/test/AddUser.test.js
  webapp/src/test/App.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/Start.test.js
  webapp/src/test/User.test.js
Labels: front-end

#54 Changes on docker-compose file
  docker-compose.yml
  question_generator/Dockerfile
  question_generator/questionService.js
Labels: back-end

#66 i18n and category filters for question generation
  .github/workflows/release.yml
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  question_generator/geography/cities/citiesQuestions.js
  question_generator/geography/cities/citiesTemplates.js
  question_generator/geography/geographyTemplate.js
  question_generator/locales/en.json
  question_generator/locales/es.json
  question_generator/package-lock.json
  question_generator/package.json
  question_generator/queryExecutor.js
  question_generator/questionGenerationService.js
  question_generator/questionGenerationService.test.js
  question_generator/questionTemplate.js
  question_generator/sports/sportTemplate.js
  question_generator/sports/tennis/tennisQuestions.js
  question_generator/sports/tennis/tennisTemplates.js
Labels: back-end
