Repository Arquisoft/wiq_es3b, pull requests merged in 2024-04, with the labels that each got.

#131 Mejora interfaz Registro de usuarios
  users/authservice/auth-model.js
  users/authservice/auth-service.js
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/assets/perfil2.jpg
  webapp/src/assets/perfil3.jpg
  webapp/src/assets/perfil4.jpg
  webapp/src/assets/perfil5.jpg
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/User.jsx
  webapp/src/css/index.css
  webapp/src/test/AddUser.test.js
  webapp/src/test/App.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/User.test.js
Labels: back-end, front-end

#133 Saving of the user who generates the questions
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/gateway-service.js
  question_generator/locales/en.json
  question_generator/locales/es.json
  question_generator/questionGenerationService.js
  users/authservice/auth-service.js
  webapp/src/components/Login.js
  webapp/src/components/Question.jsx
Labels: back-end

#147 Inicio de sesión y modos de juego
  webapp/public/favicon.ico
  webapp/public/index.html
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/public/manifest.json
  webapp/src/App.js
  webapp/src/assets/icon.png
  webapp/src/assets/perfil2.jpg
  webapp/src/assets/perfil3.jpg
  webapp/src/assets/perfil4.jpg
  webapp/src/assets/perfil5.jpg
  webapp/src/assets/vida.png
  webapp/src/audio/activate.mp3
  webapp/src/components/AddUser.js
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/index.css
  webapp/src/test/AddUser.test.js
  webapp/src/test/App.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/PostGame.test.js
  webapp/src/test/Question.test.js
  webapp/src/test/Start.test.js
  webapp/src/test/User.test.js
Labels: back-end, front-end

#152 Question generation service problems solved
  gatewayservice/gateway-service.js
  question_generator/art/artTemplate.js
  question_generator/entertainment/entertainmentTemplate.js
  question_generator/entertainment/movies/moviesQuestions.js
  question_generator/entertainment/series/seriesQuestions.js
  question_generator/entertainment/videogames/videogamesQuestions.js
  question_generator/geography/autonomous_communities_spain/autonomousCommunitiesSpainTemplates.js
  question_generator/geography/cities/citiesTemplates.js
  question_generator/geography/geographyTemplate.js
  question_generator/planets/planetsTemplates.js
  question_generator/queryExecutor.js
  question_generator/questionGenerationService.js
  question_generator/questionGenerationService.test.js
  question_generator/questionTemplate.js
  question_generator/questions-utils.js
  question_generator/sports/sportTemplate.js
  users/authservice/auth-service.test.js
  webapp/src/components/Question.jsx
Labels: back-end, front-end

#155 Users info api
  docker-compose.yml
  gameservice/game-model.js
  gameservice/game-service.js
  gameservice/game-service.test.js
  gameservice/package-lock.json
  gameservice/package.json
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  users/userservice/package-lock.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/assets/vida.png
Labels: back-end

#156 More info added for games and api-doc updated
  gameservice/game-model.js
  gameservice/game-service.js
  gameservice/game-service.test.js
  gatewayservice/openapi.yml
  webapp/e2e/steps/register-form.steps.js
  webapp/src/components/PostGame.jsx
  webapp/src/test/PostGame.test.js
Labels: documentation, back-end

#159 Documentation update
  docs/images/GameView.png
  docs/images/HomeView.png
  docs/images/UserView.png
  docs/src/04_solution_strategy.adoc
  docs/src/08_concepts.adoc
Labels: documentation

#166 Autologin, changes on displayed information and api-doc updated
  .github/workflows/build.yml
  .github/workflows/release.yml
  .vscode/settings.json
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yml
  gatewayservice/package-lock.json
  package-lock.json
  users/authservice/auth-service.js
  users/userservice/user-service.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/User.jsx
  webapp/src/test/AddUser.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/PostGame.test.js
Labels: documentation, back-end, front-end

#179 Personalización, nueva interfaz y adaptabilidad móvil
  webapp/package-lock.json
  webapp/src/App.js
  webapp/src/audio/activate.mp3
  webapp/src/components/AddUser.js
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/User.css
  webapp/src/css/addUser.css
  webapp/src/css/animatedBG.css
  webapp/src/css/game.css
  webapp/src/css/index.css
  webapp/src/css/layout.css
  webapp/src/css/login.css
  webapp/src/css/nav.css
  webapp/src/css/postGame.css
  webapp/src/css/question.css
  webapp/src/css/start.css
  webapp/src/css/users.css
  webapp/src/index.js
  webapp/src/test/Game.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/Participation.test.js
  webapp/src/test/Question.test.js
  webapp/src/test/Start.test.js
Labels: front-end

#182 i18n Completa y test
  webapp/e2e/steps/register-form.steps.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/AddUser.js
  webapp/src/components/Game.jsx
  webapp/src/components/LanguageSelect.js
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/nav.css
  webapp/src/css/users.css
  webapp/src/index.js
  webapp/src/messages/messages_en.json
  webapp/src/messages/messages_es.json
  webapp/src/test/AddUser.test.js
  webapp/src/test/App.test.js
  webapp/src/test/Game.test.js
  webapp/src/test/Login.test.js
  webapp/src/test/Nav.test.js
  webapp/src/test/Participation.test.js
  webapp/src/test/PostGame.test.js
  webapp/src/test/Question.test.js
  webapp/src/test/Start.test.js
  webapp/src/test/User.test.js
Labels: back-end, front-end

#183 Frontend CSS upgrade
  webapp/src/App.js
  webapp/src/assets/perfil2.jpg
  webapp/src/assets/perfil3.jpg
  webapp/src/assets/perfil4.jpg
  webapp/src/assets/perfil5.jpg
  webapp/src/components/AddUser.js
  webapp/src/components/Game.jsx
  webapp/src/components/Login.js
  webapp/src/components/Nav.jsx
  webapp/src/components/PostGame.jsx
  webapp/src/components/Question.jsx
  webapp/src/components/Start.jsx
  webapp/src/components/User.jsx
  webapp/src/css/addUser.css
  webapp/src/css/layout.css
  webapp/src/css/login.css
  webapp/src/css/users.css
  webapp/src/messages/messages_en.json
  webapp/src/messages/messages_es.json
Labels: front-end

#189 Friends management
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker-compose.yml
  gameservice/game-service.js
  gameservice/game-service.test.js
  gameservice/openapi.yml
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yml
  question_generator/openapi.yml
  questionservice/openapi.yml
  questionservice/question-service.js
  sonar-project.properties
  users/authservice/auth-service.js
  users/authservice/openapi.yml
  users/friendsservice/Dockerfile
  users/friendsservice/friends-model.js
  users/friendsservice/friends-service.js
  users/friendsservice/friends-service.test.js
  users/friendsservice/openapi.yml
  users/friendsservice/package-lock.json
  users/friendsservice/package.json
  users/userservice/openapi.yml
  users/userservice/user-service.js
  webapp/e2e/steps/i18n-steps.js
  webapp/package-lock.json
  webapp/src/App.js
  webapp/src/components/Friends.jsx
  webapp/src/components/Nav.jsx
  webapp/src/css/friends.css
  webapp/src/messages/messages_en.json
  webapp/src/messages/messages_es.json
  webapp/src/messages/messages_fr.json
  webapp/src/messages/messages_it.json
  webapp/src/test/Friends.test.js
  webapp/src/test/Nav.test.js
Labels: back-end, front-end, Optional

#195 Endpoint_usage, e2e tests and i18n files updated
  gatewayservice/gateway-service.js
  question_generator/locales/es.json
  question_generator/locales/fr.json
  question_generator/locales/it.json
  question_generator/questionGenerationService.js
  webapp/e2e/features/friends.feature
  webapp/e2e/features/login.feature
  webapp/e2e/features/play-classic.feature
  webapp/e2e/steps/close-session-steps.js
  webapp/e2e/steps/friends.js
  webapp/e2e/steps/i18n-steps.js
  webapp/e2e/steps/infinite-mode-steps.js
  webapp/e2e/steps/login.js
  webapp/e2e/steps/play-classic.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/e2e/user-model.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Friends.jsx
  webapp/src/test/Friends.test.js
Labels: test
